### ISSUE TITLE
Comparing extracted optional to non-optional value

### ISSUE THREAD

**Issue by lukeredpath** [pointfreeco/swift-case-paths#42]
This is a follow up to the regression discussed in #40 - the fix in #41 fixed the issues we were seeing with 0.5.0 when using a case path in a pullback, however I still had the following issue with this fix.

We have an interface that returns a `Result<T?, Error>` which we were using in a test assertion which is now failing unless I unwrap the optional. For example, given something like this:

```swift
func fetch() -> Result<String?, Error> {
  return .success("hello world")
}
```

The following assertion now fails, but used to pass:

```swift
XCTAssertEqual(
    "hello world",
    extract(case: Result.success, from: fetch())
)
```

However, this does pass:

```swift
XCTAssertEqual(
    .some("hello world"),
    extract(case: Result.success, from: fetch())
)
```

I can of course just do this:

```swift
XCTAssertEqual(.success("hello world"), fetch()))
```

I don't know if this is a blocker but I think its worth highlighting the behaviour change. @mayoff mentioned he had a possible fix for this.

**Comment by stephencelis** [comment]
@lukeredpath We merged his fix into `main` about an hour ago. Can you try your test against that to confirm? We have a few things to prep before a 0.6.0 is released, but more eyes on it would definitely be helpful!

**Comment by lukeredpath** [comment]
@stephencelis just retried against main and this is still an issue. Its not a big blocker for us because its only affecting our tests, which I can rewrite to work around this, but it does still fail.

The failure message is even more confusing to me. If I hit a breakpoint and call `fetch()` I can see it's returning a `Result<T, E>.success(value)` but if I do:

```swift
XCTAssertEqual(value, extract(case: Result.success, from: fetch())
```

XCTest gives me the failure message:

```
"XCTAssertEqual failed, (Optional(value)) is not equal to ("nil")"
```

As before, either changing value in the assertion to `.some(value)` or explicitly unwrapping the extracted value by doing `extract(case: Result.success, from: fetch())!` makes the assertion pass and I can also just do `XCTAssertEqual(.success(value), fetch())` which is probably simpler!

**Comment by mayoff** [comment]
- The unconstrained type of `Result<String?, Error>.success` is `(String?) -> Result<String?, Error>`.
- Therefore unconstrained type of `extract(case: Result.success, from: fetch())` is `String??` (note the double `Optional`).
- The unconstrained type of `"hello world"` is `String`.
- Swift is willing to promote `"hello world"` to `.some("hello world")`, but it will not promote it to `.some(.some("hello world"))`. That is, Swift will add a single layer of `Optional` if needed for type checking.
- Swift can promote a function of type `(String?) -> Result<String?, Error>` to a function of type `(String) -> Result<String?, Error>` (because `String?` is in contravariant position).

So, to make the `XCTAssertEqual` statement compile, Swift performs two promotions:

- It promotes `"hello world"` to `.some("hello world")`.
- It promotes `Result<String?, Error>.success` to `(String) -> Result<String?, Error>`.

This makes `extract(case:from:)` return type `String?` instead of type `String??`. This leads the implementation of `extract` to expect the associated value type to be `String`, but the associated value type is actually `String?`.

[This commit](https://github.com/mayoff/swift-case-paths/commit/9154dda26adda61ab2612db9e9a5a4babe924c7c) fixes the problem. I'll move it to a new branch off main and submit a pull request shortly.

**Comment by stephencelis** [comment]
Thanks @mayoff for diving in once again! Amazing what optional promotion does to simple runtime analysis 😅

Hopefully Swift gets proper case paths in the language eventually, and hopefully these edge cases are dwindling in number...

**Comment by lukeredpath** [comment]
@stephencelis @mayoff thanks again for your work on this. I've just updated our dependency to 0.6.0 and our full test suite is now passing.
