### ISSUE TITLE
EXC_BREAKPOINT from version 0.6.0

### ISSUE THREAD

**Issue by MatejkaMartin** [pointfreeco/swift-case-paths#51]
Hi, 

i would like to ask you, if you have any idea what we are doing wrong. Some changes made from 0.5.0 to 0.6.0 cause us some issues. In our case it happens when we sent a action to present alert. I don't see anything special. The action has a basic, not complicated structure with few attributes as the associated value. The action is observed by parent reducer and it presents alert. I tried to found the changes made from 0.5.0 to 0.6.0 which can cause the problem. You can find them on the screenshot.

Thx for help. 
![Snímek obrazovky 2021-07-29 v 13 36 52](https://user-images.githubusercontent.com/17528892/127623839-abbcf2bc-2471-49dc-8a9c-d9ceab1d761e.png)
![Snímek obrazovky 2021-07-29 v 13 51 34](https://user-images.githubusercontent.com/17528892/127623863-27ed821a-4ae8-4c50-8157-3fea81727e85.png)

**Comment by iampatbrown** [comment]
Have you tried with v0.7.0?

**Comment by stephencelis** [comment]
@MatejkaMartin I think you're seeing #45, which was fixed in #46. As @iampatbrown mentioned, upgrading to 0.7.0 should hopefully eliminate the problem!

**Comment by MatejkaMartin** [comment]
Thx for responses. I tried also the new version 0.7.0 and actually we have still the same issue. :(
![Snímek obrazovky 2021-07-30 v 15 00 10](https://user-images.githubusercontent.com/17528892/127656612-41bba8b6-db61-4236-aabd-a3bee9d9af16.png)

**Comment by stephencelis** [comment]
@MatejkaMartin Can you provide some working code that reproduces the issue? Without knowing the structure of the enum you're trying to extract it'll be tough for us to debug the problem.

**Comment by mayoff** [comment]
@MatejkaMartin If you can reproduce the stack trace you posted:

1. Click on frame 6 (`Strategy.extract(from:tag:)`) in the stack trace.
2. Then, in the lldb console, execute the command `p self`.
3. Also in the lldb console, execute the command `p root`.

Copy the lldb output into this issue.

**Comment by stephencelis** [comment]
@MatejkaMartin We just merged @mayoff's fix for a similar issue that crashed at that same line. Can you try your code against the `main` branch and see if that helps?
